version: "3"

services:
  rethinkdb:
    image: rethinkdb:2.3.6
    restart: always

  redis:
    image: redis:3.2.8

  web:
    image: parabol-action:latest
    build: .
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - rethinkdb
      - redis
    links:
      - redis
      - rethinkdb
    env_file:
      - ./packages/server/.env
    entrypoint: ./docker_entrypoint.sh
    command: yarn start
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
volumes:
  app_node_modules:

