version: "3"

services:
  redis:
    image: redis:3.2.8

  rethinkdb:
    image: rethinkdb:2.3.6
    restart: always

  web:
    image: parabol-action:latest
    container_name: parabol-action
    build: .
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rethinkdb
    links:
      - redis
      - rethinkdb
    env_file:
      - ./packages/server/.env
    entrypoint: ./docker_entrypoint.sh
    command: yarn start
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
      - app_build:/usr/src/app/build
volumes:
  app_node_modules:
  app_build:

